image:
  file: .docker/.gitpod.Dockerfile
ports:
- port: 8002
  visibility: public
vscode:
  extensions:
    - formulahendry.vscode-mysql@0.4.1
tasks:
  - name: "Run services and install Magento"
    openMode: tab-after
    init: ./.docker/init.sh
    command: ./.docker/services.sh;
             ./.docker/build.sh;
