image:
  file: .docker/.gitpod.Dockerfile
ports:
- port: 8002
  visibility: public
vscode:
  extensions:
    - mtxr.sqltools@0.28.0
    - mtxr.sqltools-driver-mysql@0.6.0
tasks:
  - name: "Run services and install Magento"
    openMode: tab-after
    init: ./.docker/scripts/init.sh
    command: ./.docker/scripts/services.sh;
             ./.docker/scripts/build.sh;
