image:
  file: .docker/.gitpod.Dockerfile
ports:
- port: 8002
  visibility: public
vscode:
  extensions:
    - TabNine.tabnine-vscode@3.4.14
    - felixfbecker.php-debug@1.16.0
tasks:
  - init: ./.docker/init.sh
  - name: "Run services and install Magento"
    openMode: tab-after
    command: service nginx start &
             sudo sed -i 's/^\(\[supervisord\]\)$/\1\nnodaemon=true/' /etc/supervisor/supervisord.conf &&
             sudo /etc/init.d/supervisor start & \
             gp ports await 3306;
             sudo supervisorctl stop mysql;
             sudo mv /var/lib/mysql $GITPOD_REPO_ROOT/;
             sed -i 's#/var/lib/mysql#'$GITPOD_REPO_ROOT'/mysql#g' /etc/mysql/conf.d/mysqld.cnf;
             sudo sed -i 's#/var/lib/mysql#'$GITPOD_REPO_ROOT'/mysql#g' /etc/supervisor/conf.d/mysql.conf;
             sudo supervisorctl update;
             sudo supervisorctl reload;
             gp ports await 3306;
             ./.docker/build.sh
